#Login Page Elements
first_name="id:first-name"
last_name="id:last-name"
job_title="id:job-title"
edu_high_school="id:radio-button-1"
edu_college="id:radio-button-2"
edu_grad_school="id:radio-button-3"
sex_male="id:checkbox-1"
sex_female="id:checkbox-2"
sex_prefer_not="id:checkbox-3"
experience="id:select-menu"
date="id:datepicker"
#submit="css:.btn.btn-lg.btn-primary"
submit="css:a.btn.btn-lg.btn-primary"
