#Registration Page locators
Register_link="xpath:/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/a"
First_Name="name:firstName"
Last_Name="name:lastName"
Phone="xpath:/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[4]/td[2]/input"
Email="name:userName"
Address="name:address1"
City="name:city"
State="name:state"
Postal_Code="name:postalCode"
Country_List="name:country"
User_Name="id:email"
Password="name:password"
ConfirmPassword="name:confirmPassword"
Click_Submit="name:submit"
